### ISSUE TITLE
Could you explain better why there is no sense to use it?

### ISSUE THREAD

**Issue by publicocean0** [cheshir/logrustash#13]
Currently there is no sense to use it. You can get the same behaviour with newest version of package and "smart" TCP connection that will provide reconnects and async behaviour

What  newest version of package?

**Comment by cheshir** [comment]
Here is original repo that I forked when author has been working on new one version and stopped accepting PRs: https://github.com/bshuster-repo/logrus-logstash-hook. 

Now new version of original package is available and here is thread about adding reconnects to it: https://github.com/bshuster-repo/logrus-logstash-hook/issues/48.

But of course you can still use "old API". It's even updated periodically.
