### ISSUE TITLE
Undefined: logrus.DefaultTimestampFormat

### ISSUE THREAD

**Issue by htfy96** [cheshir/logrustash#5]
They made it private at https://github.com/sirupsen/logrus/commit/abee6f9b0679f8044f5fca552eb6a9691a55d4ac

Fixes for https://github.com/x-cray/logrus-prefixed-formatter/pull/21/commits/5f3f20032b23eb0c7d45b57d5f30a65fe5dc0f5b

**Comment by htfy96** [comment]
Sorry. I just found it was already merged at https://github.com/cheshir/logrustash/pull/4/commits/54d6244e08117df67a88ec47b47048d7771d66ad

**Comment by cheshir** [comment]
Hi, @htfy96.
I've added release tag 0.7.1. Thanks for your advice!
